### ISSUE TITLE
GenerateEndpointId always returns same value (on Windows)

### ISSUE THREAD

**Issue by temppost2** [willamowius/gnugk#11]
I built gnugk on Windows without SSL support.
Source code of **RegistrationTable::GenerateEndpointId** for me looks like this:

```
void RegistrationTable::GenerateEndpointId(H225_EndpointIdentifier & NewEndpointId, PString prefix)
{
    do {
        unsigned randomNum;
        randomNum = rand();
        NewEndpointId = prefix + PString(PString::Unsigned, randomNum) + endpointIdSuffix;
        // check if new ID doesn't already exists (unlikely, but...)
    } while (FindByEndpointId(NewEndpointId));
}

```

Because call to **srand** (see Toolkit.cxx) is thread-local, every call to **rand** returns 41.
As a result all generated endpoint ids are the same (41_endp)

**Comment by willamowius** [comment]
On Unix calling srand() once on startup is the correct thing and on Windows you shouldn't get the same endpoint ID while it is still in use.

I added a patch that initializes the random number generator for every worker thread on Windows, but using OpenSSL is the much better solution.
