### ISSUE TITLE
the proxy call can not be established  when the gnugk behind NAT 

### ISSUE THREAD

**Issue by jiangjianping** [willamowius/gnugk#13]
1.  gnugk located behind the NAT with public externalIP
2. proxy is enabled
3.  the two eps registered with gnugk
4. One ep call another, the call can be received, but the h45 can not be established because the h245 address returned from gnugk  is private, not the externalIP as expected

**Comment by willamowius** [comment]
This is a very common scenario that I have seen work fine many times.

If this really fails in your configuration, please contact me by email with more details.
