### ISSUE TITLE
Consult gnugk avaya support for suggestions on functional interfaces

### ISSUE THREAD

**Issue by xunlujiehuo** [willamowius/gnugk#15]
Hello, I am using avaya 1608 to register on gnugk. Now I can implement simple call functions. I have improved the call hold button. Now I want to make the function menu displayed on the avaya 1608 phone. I have changed the featureSet in gatekeeperConfirm. parameters, but the effect is not ideal, can you give me some suggestions in this regard?

**Comment by willamowius** [comment]
Please link to your changes, otherwise nobody will be able to comment.

**Comment by xunlujiehuo** [comment]
I don’t know much about the h323 protocol. I am a novice on h323. Compared with Avaya’s IPO system, I added support for id = standard 13 id = standard 14 id = standard 15 to the featureSet in gatekeeperConfirm.

**Comment by xunlujiehuo** [comment]
This is the gatekeeperConfirm I return
gatekeeperConfirm {
    requestSeqNum = 8
    protocolIdentifier = 0.0.8.2250.0.2
    rasAddress = ipAddress {
      ip =  4 octets {
        c0 a8 01 65                                        ...e
      }
      port = 1719
    }
    authenticationMode = pwdSymEnc <<null>>
    tokens = 1 entries {
      [0]={
        tokenOID = 0.0
        timeStamp = 1697606861
        random = 340095662
        generalID =  11 characters {
          0044 0045 0046 0049 004e 0049 0054 0059   DEFINITY
          002d 0047 004b                            -GK
        }
      }
    }
    algorithmOID = 2.16.840.1.114187.1.3
    featureSet = {
      replacementFeatureSet = true
      desiredFeatures = 1 entries {
        [0]={
          id = oid 2.16.840.1.114187.1.10
          parameters = 15 entries {
            [0]={
              id = standard 1
            }
            [1]={
              id = standard 2
            }
            [2]={
              id = standard 3
            }
            [3]={
              id = standard 5
            }
            [4]={
              id = standard 6
            }
            [5]={
              id = standard 7
            }
            [6]={
              id = standard 9
            }
            [7]={
              id = standard 10
            }
            [8]={
              id = standard 11
            }
            [9]={
              id = standard 13
            }
            [10]={
              id = standard 14
            }
            [11]={
              id = standard 15
            }
            [12]={
              id = standard 17
            }
            [13]={
              id = standard 18
            }
            [14]={
              id = standard 19
            }
          }
        }
      }
      supportedFeatures = 1 entries {
        [0]={
          id = oid 2.16.840.1.114187.1.10
          parameters = 15 entries {
            [0]={
              id = standard 1
            }
            [1]={
              id = standard 2
            }
            [2]={
              id = standard 3
            }
            [3]={
              id = standard 5
            }
            [4]={
              id = standard 6
            }
            [5]={
              id = standard 7
            }
            [6]={
              id = standard 9
            }
            [7]={
              id = standard 10
            }
            [8]={
              id = standard 11
            }
            [9]={
              id = standard 13
            }
            [10]={
              id = standard 14
            }
            [11]={
              id = standard 15
            }
            [12]={
              id = standard 17
            }
            [13]={
              id = standard 18
            }
            [14]={
              id = standard 19
            }
          }
        }
      }
    }
  }

**Comment by xunlujiehuo** [comment]
This is the previous gatekeeperRequest request of avaya and the gatekeeperConfirm reply of gnugk
gatekeeperRequest {
    requestSeqNum = 8
    protocolIdentifier = 0.0.8.2250.0.2
    nonStandardData = {
      nonStandardIdentifier = object 2.16.840.1.113778.4.2.1
      data =  3 octets {
        85 01 40                                           ..@
      }
    }
    rasAddress = ipAddress {
      ip =  4 octets {
        c0 a8 01 21                                        ...!
      }
      port = 49304
    }
    endpointType = {
      terminal = {
      }
      mc = false
      undefinedNode = false
    }
    endpointAlias = 1 entries {
      [0]=dialedDigits "1000"
    }
    tokens = 1 entries {
      [0]={
        tokenOID = 2.16.840.1.114187.1.6.2
        dhkey = {
          halfkey = Hex {
            a1 ea 85 05 3c f6 b5 b1  39 cc 18 a5 db 3b 40 3c 
            fe 0e ec f4 f5 aa e9 41  3c fe 51 bb 5f 51 58 28 
            65 73 a8 b7 25 03 18 d4  63 16 83 b7 86 e7 d8 ec 
            be e9 62 45 97 58 73 b6  f5 a9 73 01 d7 32 ad 22 
            e4 30 6c dc 4b 9a e9 99  15 31 12 67 1f 55 34 be 
            46 bd cd ca 25 2f a3 2b  cf 5e f2 61 f3 e6 d8 04 
            41 6f 3d ee d9 b2 12 c3  0b 60 e4 21 d6 28 5d 3e 
            42 4c 77 bd db f0 13 48  9e e0 f7 04 8d 14 2d 34           }
          modSize = 
          generator = 
        }
        profileInfo = 2 entries {
          [0]={
            elementID = 2
            element = octets  4 octets {
              00 00 60 94                                        ..`.
            }
          }
          [1]={
            elementID = 1
            element = octets  12 octets {
              4f 9a 00 00 03 64 00 00  30 d4 4f 9b               O....d..0.O.
            }
          }
        }
      }
    }
    authenticationCapability = 2 entries {
      [0]=pwdSymEnc <<null>>
      [1]=keyExch 2.16.840.1.114187.1.6.2
    }
    algorithmOIDs = 2 entries {
      [0]=1.3.14.3.2.6
      [1]=2.16.840.1.114187.1.3
    }
    featureSet = {
      replacementFeatureSet = false
      supportedFeatures = 1 entries {
        [0]={
          id = oid 2.16.840.1.114187.1.10
          parameters = 8 entries {
            [0]={
              id = standard 5
            }
            [1]={
              id = standard 9
            }
            [2]={
              id = standard 10
            }
            [3]={
              id = standard 11
            }
            [4]={
              id = standard 13
            }
            [5]={
              id = standard 14
            }
            [6]={
              id = standard 15
            }
            [7]={
              id = standard 16
            }
          }
        }
      }
    }
  }


gatekeeperConfirm {
    requestSeqNum = 78
    protocolIdentifier = 0.0.8.2250.0.2
    rasAddress = ipAddress {
      ip =  4 octets {
        c0 a8 01 65                                        ...e
      }
      port = 1719
    }
    authenticationMode = pwdSymEnc <<null>>
    tokens = 1 entries {
      [0]={
        tokenOID = 0.0
        timeStamp = 1697083637
        random = 44388513
        generalID =  11 characters {
          0044 0045 0046 0049 004e 0049 0054 0059   DEFINITY
          002d 0047 004b                            -GK
        }
      }
    }
    algorithmOID = 2.16.840.1.114187.1.3
    featureSet = {
      replacementFeatureSet = true
      desiredFeatures = 3 entries {
        [0]={
          id = oid 2.16.840.1.114187.1.10
          parameters = 12 entries {
            [0]={
              id = standard 1
            }
            [1]={
              id = standard 2
            }
            [2]={
              id = standard 3
            }
            [3]={
              id = standard 5
            }
            [4]={
              id = standard 6
            }
            [5]={
              id = standard 7
            }
            [6]={
              id = standard 9
            }
            [7]={
              id = standard 10
            }
            [8]={
              id = standard 11
            }
            [9]={
              id = standard 17
            }
            [10]={
              id = standard 18
            }
            [11]={
              id = standard 19
            }
          }
        }
        [1]={
          id = oid 2.16.840.1.114187.1.9
          parameters = 5 entries {
            [0]={
              id = standard 1
              content = number8 1
            }
            [1]={
              id = standard 2
              content = number16 60
            }
            [2]={
              id = standard 3
              content = number16 0
            }
            [3]={
              id = standard 4
              content = bool true
            }
            [4]={
              id = standard 5
              content = bool true
            }
          }
        }
        [2]={
          id = standard 6
        }
      }
      supportedFeatures = 3 entries {
        [0]={
          id = oid 2.16.840.1.114187.1.10
          parameters = 12 entries {
            [0]={
              id = standard 1
            }
            [1]={
              id = standard 2
            }
            [2]={
              id = standard 3
            }
            [3]={
              id = standard 5
            }
            [4]={
              id = standard 6
            }
            [5]={
              id = standard 7
            }
            [6]={
              id = standard 9
            }
            [7]={
              id = standard 10
            }
            [8]={
              id = standard 11
            }
            [9]={
              id = standard 17
            }
            [10]={
              id = standard 18
            }
            [11]={
              id = standard 19
            }
          }
        }
        [1]={
          id = oid 2.16.840.1.114187.1.9
          parameters = 5 entries {
            [0]={
              id = standard 1
              content = number8 1
            }
            [1]={
              id = standard 2
              content = number16 60
            }
            [2]={
              id = standard 3
              content = number16 0
            }
            [3]={
              id = standard 4
              content = bool true
            }
            [4]={
              id = standard 5
              content = bool true
            }
          }
        }
        [2]={
          id = standard 6
        }
      }
    }
  }

**Comment by xunlujiehuo** [comment]
I hope Avaya can enter the feature menu through the feature button. Now this gnugk avaya supported version, the feature button does not send any signaling.

**Comment by xunlujiehuo** [comment]
@kprokazov  @willamowius    Hello, I am working on gnugk to support the function menu bar of avaya 1608. I want to know the feasibility of this work and whether it is possible to implement the function menu like the IPO.

**Comment by kprokazov** [comment]
I think this is possible, but requires a LOT of time for reverse-engineering and testing of protocol parameters sent to phone via CCMS. Also, it much simplier to process if you will use CM debugging capabilities, not IPO one... but IPO have their own "features" itself.

**Comment by kprokazov** [comment]
In any case modifying FeatureSets is completely not enough to perform such task.

**Comment by xunlujiehuo** [comment]
> 无论如何，修改功能集完全不足以执行此类任务。
Hello, I sincerely ask you if you can give me any advice in this regard, such as
static const unsigned char CCMS_loginRequest_1000[] = {
	0x09, 0x81,	/* Len, Cmd ? */
	0x01, 0x00,	/* forceLogin */
	0x26, 0x1e, 0x9e, 0x00, 0x01, 0x20,		/* ? */

	0x01, 0x00,	/* emergencyCallHandling */
	0x06, 0xb4, 0xb0, 0x17, 0x8d, 0x29, 0xc6,	/* macAddress */
	0x01, 0x00,
	0x05, 0xc0, 0x02, 0x00, 0x00, 0x2f,		/* unicodeScript */
	0x01, 0x00,	/* ttiCapable */
	0x01, 0x80,	/* sendButtonInfo */
	0x01, 0x00,	/* sendSwitchRelease */
	0x01, 0x00	/* sendStationInfo */
/*
	forceLogin FALSE,
	audioCapable TRUE,
	callSigProtocol h323AnnexL-P : NULL,
	connectionType lan : NULL,
	emergencyCallHandling emerExtension : NULL,
	macAddress 'B4B0178D29C6'H,
	signalingChannelRecoveryAlgorithmVersion 1,
	unicodeScript 33554479,
	ttiCapable NULL,
	sendButtonInfo TRUE,
	sendSwitchRelease NULL,
	sendStationInfo NULL
*/
};

In your code, what is the meaning of the comment part? I would like to know how to get the comment information based on the encoding, and what form of encryption is used by avaya phone， OID_AVAYA_Feature9[] = "2.16.840.1.114187.1.9"; What does this encryption method mean? Is it Avaya's own encryption method?

**Comment by kprokazov** [comment]
This data was received from decoded signalling part between CM and phone itself. There are no documentation on this, only parts, which we can reverse-engineer via tracer (MTA) and/or debugger. About encryption - do you mean signalling encryption? If yes - it can be AES or AEA (Avaya's private). I can try to help you with in-menu buttons (features), seems in middle of the Nov.

**Comment by xunlujiehuo** [comment]
> 该数据是从 CM 和电话本身之间的解码信令部分接收的。没有关于此的文档，只有部分内容，我们可以通过跟踪器（MTA）和/或调试器对其进行逆向工程。关于加密 - 您是指信令加密吗？如果是 - 可以是 AES 或 AEA（Avaya 专用）。我可以尝试帮助您使用菜单内按钮（功能），似乎是在 11 月中旬。



I would really appreciate your help in trying to do this. I reproduced the display of the function menu by completely copying the coded signaling of the IPO avaya 1608 phone. The features  menu can now be displayed. I will continue to do the features in the features  menu。   I saw that there is a reverse part about signaling in your code. I really want to know if the reverse information can be obtained based on these coded signaling.  For example, this part  
static const unsigned char CCMS_vdtUpdate_loadDisplayRingerOff[] = {
/*	0x13,			 Len 19 */
	0x16,
	0x38, 0x11, 0x20,	/* 81A0501 */
/**/
	0xa2, 0x80, 0x05, /* ? */
	0x40,				/* ringerChange = Off */
	0xad, 0xe3,			/* loadDisplay */
	0x1b, 0x5b, 0x00, 0x3b, 0x00, 0x48, /* esc[;H */
	0x1b, 0x5b, 0x02, 0x4b, 0x01, 0x3d	/* esc[stxKsoh= */
};

I really want to know how to obtain ringerChange = Off loadDisplay through this encoding information.

**Comment by xunlujiehuo** [comment]
> > 该数据是从 CM 和电话本身之间的解码信令部分接收的。没有关于此的文档，只有部分内容，我们可以通过跟踪器（MTA）和/或调试器本身进行逆向工程。关于加密 -您是指信令加密吗？如果是 - 可以是 AES 或 AEA（Avaya 专用）。我可以尝试帮助您使用菜单内按钮（功能），好像是在 11 月中旬。
> 
> 我非常感谢您在尝试做到这一点时提供的帮助。我通过完全复制IPO avaya 1608电话的编码信令来重现功能菜单的显示。现在可以显示功能菜单。我会继续做功能菜单中的功能。我看到你的代码中有一个关于信令的反向部分。我很想知道是否可以根据这些编码信令获得反向信息。例如这部分 static const unsigned char CCMS_vdtUpdate_loadDisplayRingerOff[] = { /* 0x13, Len 19 _/ 0x16, 0x38, 0x11, 0x20, /_ 81A0501 _/ /**/ 0xa2, 0x80, 0x05, /_ ? _/ 0x40, /_ ringerChange = 关闭_/ 0xad, 0xe3, /_ loadDisplay _/ 0x1b, 0x5b, 0x00, 0x3b, 0x00, 0x48, /_ esc[;H _/ 0x1b, 0x5b, 0x02, 0x4b, 0x01, 0x3d /_ esc[stxKsoh= * / };
> 
> 我很想知道如何通过这个编码信息获取ringerChange = Off loadDisplay。
I am trying to fully reproduce the functions of avaya 1608. I think it is very difficult to completely copy the signaling. I hope to configure the features of multiple avaya phones. This involves a huge amount of information

**Comment by xunlujiehuo** [comment]
After a long period of hard work, I have matched most of the functions of avaya 1608. I will consider publishing it later

**Comment by willamowius** [comment]
Wow, thats great! Please let me know if you want me help find testers before you are ready to release.

**Comment by xunlujiehuo** [comment]
After a long period of hard work and the help of colleagues, I have adapted to Avaya 1608-I and 90% of the functions and displays of the 9608 phone. I will consider whether to publish it. Although my code is terrible, it contains a lot of Avaya's own signaling content, which will take a long time to extract. If you have some ideas about adapting Avaya phones, you can Contact me, I have some little experience with this method, this is my email xunlujiehuo@gmail.com

**Comment by xunlujiehuo** [comment]
> 经过长时间的努力和同事们的帮助，我已经适配了Avaya 1608-I和9608电话90%的功能和显示。我会考虑是否发布。虽然我的代码很糟糕，但其中包含了大量Avaya自己的信令内容，提取起来会花很长时间。如果你对适配Avaya电话有一些想法，可以联系我，我对这种方法有一些小经验，这是我的邮箱[xunlujiehuo@gmail.com](mailto:xunlujiehuo@gmail.com)



> 经过长时间的努力和同事们的帮助，我已经适配了Avaya 1608-I和9608电话90%的功能和显示。我会考虑是否发布。虽然我的代码很糟糕，但其中包含了大量Avaya自己的信令内容，提取起来会花很长时间。如果你对适配Avaya电话有一些想法，可以联系我，我对这种方法有一些小经验，这是我的邮箱[xunlujiehuo@gmail.com](mailto:xunlujiehuo@gmail.com)



> 经过长时间的努力和同事们的帮助，我已经适配了Avaya 1608-I和9608电话90%的功能和显示。我会考虑是否发布。虽然我的代码很糟糕，但其中包含了大量Avaya自己的信令内容，提取起来会花很长时间。如果你对适配Avaya电话有一些想法，可以联系我，我对这种方法有一些小经验，这是我的邮箱[xunlujiehuo@gmail.com](mailto:xunlujiehuo@gmail.com)



> After a long period of hard work and the help of colleagues, I have adapted to Avaya 1608-I and 90% of the functions and displays of the 9608 phone. I will consider whether to publish it. Although my code is terrible, it contains a lot of Avaya's own signaling content, which will take a long time to extract. If you have some ideas about adapting Avaya phones, you can Contact me, I have some little experience with this method, this is my email [xunlujiehuo@gmail.com](mailto:xunlujiehuo@gmail.com)

So far, the work on avaya is coming to an end for me. I have completed the adaptation of 1608-I 9608 9640G J179 1603SW-I phones. They are all based on the H323 protocol and already have More than 90% of the functions are very versatile for phone signaling between 16XX 96X1 96X0 series. If anyone needs to do work in this area, you can contact me by email.
