### ISSUE TITLE
WARNING: Config section [Routing::Sql] unknown

### ISSUE THREAD

**Issue by slesru** [willamowius/gnugk#16]
Hello!

5.11 have this warning if only sqlite is in use, 5.10 works just fine.
Looks like #define HAS_DATABASE
solves problem

**Comment by willamowius** [comment]
Thanks for your bug report, but I'm having trouble to repliacte the issue.

Can you please make sure you do a "make clean" before you build GnuGk and report back ?

**Comment by slesru** [comment]
I just built it again after make clean
and it works as expected.

Looks like this is result of missing -devel packages, I got during configure, then I installed them and run configure again, but...

Thank you!
