### ISSUE TITLE
when use parent mode caused RRJ

### ISSUE THREAD

**Issue by hiyaya007** [willamowius/gnugk#18]
I want to use parent gnugk mode, and i set the gatekeeper.ini as follows:
[Endpoint]
Gatekeeper=10.20.51.43
but it caused an error as invalidsignaladdress.
Looking forward to your reply.
![微信图片_20240424141011](https://github.com/willamowius/gnugk/assets/167958109/8fe5a9ad-c063-4c10-b9c7-29c38cbced6d)

**Comment by willamowius** [comment]
You need to find out why it is using port 0 for the callSignalAddress. That doesn't happen when I use GnuGk as a child.
If you want me to debug this, please contact me directly.

**Comment by willamowius** [comment]
Please check your config that GnuGk is at least in routed mode. A child gatekeeper may not run in direct mode.

You should see the error message "Error: Child gatekeeper may not run in direct mode!" in your trace.
