### ISSUE TITLE
how to listen 1719

### ISSUE THREAD

**Issue by qszxnp** [willamowius/gnugk#3]
i use avaya 1608, and set the gnugk as gateway.when is start, the telephon send and udp pkg port 1719(tcpdump and see) to gnuk,but gnugk do not listen 1719

**Comment by willamowius** [comment]
GnuGk will listen to UDP 1719 unless you configure it to use a different port with the UnicastRasPort= switch.

The more likely cause of you issue is that most Avaya phones that claim to be H.323 compliant are not. They speak a "version of H.323" that is only comaptible with other Avaya devices and not with the ITU standard.

**Comment by qszxnp** [comment]
thx, it is my fault, i use netstat -lntp ，and miss udp 。sry
