### ISSUE TITLE
ras comfirm

### ISSUE THREAD

**Issue by qszxnp** [willamowius/gnugk#4]
hi, i use gnugk as h323 gateway  and try to register my avaya ip phone 。
   after configue the gnugk gateway，ip phone restart again and again. so i tcpdump and find  the ras gatekeeper req contain many items  as ras-req.jpg and ras gatekeeper comfirm just contain ip addr  as ras-comfirm.jpg
   i think that is the reason i can not register the phone.
   i need to modify some gnugk config?
![ras-req](https://user-images.githubusercontent.com/6102619/59647813-4980e880-91af-11e9-8cc3-b3eb1650d61c.jpg)
![ras-comfirm](https://user-images.githubusercontent.com/6102619/59647852-759c6980-91af-11e9-8a6f-4f5ef3771bb5.jpg)

**Comment by qszxnp** [comment]
i have a gatekeeper,and i dump the worked ras pkg ,it works well
![online1](https://user-images.githubusercontent.com/6102619/59647966-de83e180-91af-11e9-944f-ec1b891c0cc8.jpg)
![online2](https://user-images.githubusercontent.com/6102619/59647968-de83e180-91af-11e9-9339-86892f341e98.jpg)

**Comment by willamowius** [comment]
Is that still the Avaya 1608 phone ? I don't think its compatible with regular H.323. As you see in the 2nd trace, they use a lot of non-standard messages that only Avaya knows about.

What brand and model is the other gatekeeper that it works with ?

**Comment by qszxnp** [comment]
hah avaya s8800.....

**Comment by qszxnp** [comment]
after set H323_H235  in h323plus-1_27_0 and gnugk, i pass the ras  and now block at registrationRequest haha

**Comment by willamowius** [comment]
You probably won't be able to get it to work. Its not just a problem with your config. Avaya uses a lot of non-standard messages and not regular H.323. If you should manage to get the phone to register, then the calls won't work. Sorry!
