### ISSUE TITLE
Does gnugk support redis?

### ISSUE THREAD

**Issue by CinderellaM** [willamowius/gnugk#5]
Hi，I`m a new bee to gnuk，and I want to use redis within gnugk ,but I can`t find any redis module in source code.
does gnuk support redis? If not,how can i do to deal with it?

PS:I`m learning english..

thanks!!!

**Comment by willamowius** [comment]
Currently GnuGk doesn't have a redis driver. What do you want to store in redis ?

**Comment by willamowius** [comment]
The latest release of GnuGk now supports redis.
