### ISSUE TITLE
no viable conversion from 'PString' to 'PIPSocket::Address'

### ISSUE THREAD

**Issue by ajacoutot** [willamowius/gnugk#7]
Hi.

I am seeing a build gnugk-5.5 failure building on OpenBSD current.

```bash
Toolkit.cxx:3257:26: error: no viable conversion from 'PString' to 'PIPSocket::Address'
                    PIPSocket::Address gkip = retval[0];
                                       ^      ~~~~~~~~~
```

```bash
$ c++ --version 
OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
Target: amd64-unknown-openbsd6.7
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by willamowius** [comment]
I have put a fix into master, but I don't have  a clang 8.0.1 handy to test.
Can you please test if this fixes the issue on OpenBSD ? If it does, I'll backport the fix to v5_5_STABLE.

**Comment by ajacoutot** [comment]
Hi @willamowius 
The fix worked fine, thank you very much.

**Comment by willamowius** [comment]
Hi @ajacoutot 

I have backported the fix to v5_5_STABLE now
