### ISSUE TITLE
Is it a bug in building GCF

### ISSUE THREAD

**Issue by StarSkyYe** [willamowius/gnugk#9]
When endpoint supports H235_AuthenticationMechanism::e_keyExch, gnugk should add a Token；
But when checking endpoint support H235_AuthenticationMechanism::e_keyExch or not, the code always search in request.m_authenticationCapability[0] ; As for the code, it uses 'For' grammar， I guess it should be coded by searching in request.m_authenticationCapability[i], not alway in [0];

Please Check for it.

the origin codes shows:
         // H.235.TSSM
        if (request.HasOptionalField(H225_GatekeeperRequest::e_authenticationCapability) &&
            request.HasOptionalField(H225_GatekeeperRequest::e_algorithmOIDs)) {
            for (PINDEX i = 0; i < request.m_authenticationCapability.GetSize(); i++) {
                if (request.m_authenticationCapability[0].GetTag() == H235_AuthenticationMechanism::e_keyExch) {
                    const PASN_ObjectId & oid = request.m_authenticationCapability[0];
                    if (oid == OID_TSSM) {
                        // add TSSM token
                        gcf.IncludeOptionalField(H225_GatekeeperConfirm::e_tokens);
                        // don't overwrite pwdSymEnc token
                        gcf.m_tokens.SetSize(gcf.m_tokens.GetSize() + 1);
                        gcf.m_tokens[gcf.m_tokens.GetSize() - 1].m_tokenOID = OID_TSSM;
                        gcf.m_tokens[gcf.m_tokens.GetSize() - 1].IncludeOptionalField(H235_ClearToken::e_timeStamp);
                        gcf.m_tokens[gcf.m_tokens.GetSize() - 1].m_timeStamp = (int)time(NULL);
                    }
                }
            }
        }

**Comment by willamowius** [comment]
Thanks for your comment, but GnuGk so far doesn't actually support any authentication algorithm that uses e_keyExch.

The code that you are looking at is a test bed for the proposed, but never ratified "H.235 TSSM" to allow endpoints to sync their clock to the gatekeeper for generating password hashes. (https://www.itu.int/md/T13-SG16-C-0704/en)

If you have endpoints that support e_keyExch and want to implement support for that in GnuGk, please contact my by email.
